### ISSUE TITLE
Jakub Racek - January 28th - Live programming Pipes and Streams

### ISSUE THREAD

**Issue by JakubRacek** [lnug/speak#11]
Description will come

**Comment by orliesaurus** [comment]
Hey @JakubRacek - are you still available :D Need a small description for the newsletter! thank you

**Comment by JakubRacek** [comment]
Hey guys, I am sorry I can't manage that. I am moving to Portugal :)

**Comment by orliesaurus** [comment]
Obrigado thx for letting me know in advance! Best of luck
